Repository nextcloud/groupware, pull requests merged in 2022-08, with the labels that each got.

#51 Create fixup workflow
  .github/workflows/fixup.yml
Labels: 3. to review, technical debt

#48 Add alpha beta steps on processes
  processes/app_release.md
Labels: 3. to review

#52 Adding naming conventions for different types of releases
  processes/app_release.md
Labels: 3. to review, documentation
